apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migrate
  namespace: catalog
spec:
  template:
    spec:
      serviceAccountName: catalog-migrator-sa
      containers:
      - name: flyway
        image: flyway/flyway:9
        args:
          - "-url=jdbc:postgresql://$(DB_HOST):5432/shopsphere"
          - "-user=$(DB_USER)"
          - "-password=$(DB_PASS)"
          - "migrate"
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: shopsphere-db-config
              key: host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: shopsphere-db-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: shopsphere-db-secret
              key: password
        volumeMounts:
        - name: migrations
          mountPath: /flyway/sql
      restartPolicy: OnFailure
      volumes:
      - name: migrations
        configMap:
          name: flyway-migrations
