# Exposes your Argo CD service to the internet via ALB.
# Uses the TLS certificate from cert-manager for HTTPS.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:  # Tells Kubernetes to use the ALB Ingress controller and cert-manager.
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:246412345195:certificate/e6f44dd0-0374-41b3-9bf7-ee21ec43815f

spec:
  rules:  #  Maps the domain to your Argo CD service.
  - host: argocd-dev.hellosaanvika.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
