apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user
  namespace: argocd
spec:
  project: shopsphere-devops
  source:
    repoURL: 'https://github.com/shopsphere-devops/helm-charts.git'
    targetRevision: main
    path: charts/user
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: user
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
